# Generated by Django 3.0.2 on 2020-01-28 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('notice_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
